spring:
  application:
    name: marketing-crm
  datasource:
    url: jdbc:postgresql://localhost:5432/marketingcrm
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080
